/-
  PZFC — skeleton.

  This file formalises the *load-bearing structural claim* of notes/00 §3:

      if the probe complex is a simplex, every compatible model glues.

  That is the precise sense in which "linear time with a perfect record" is
  structurally blind to contextuality: not that it fits badly, but that on such
  a complex the obstruction is identically zero, so the phenomenon cannot even
  be stated.

  Deliberately mathlib-free: possibilistic (support-based) models rather than
  probabilistic ones.  All the numerical content lives in src/pzfc/ instead.
  Nothing here is `sorry`; the open problems are in notes/04, not in this file.
-/

namespace PZFC

/-- A probe complex: which questions exist, what they can answer, and which of
    them may be asked together.  `member C q` reads "probe `q` belongs to
    context `C`".  Note we never require the induced compatibility relation to
    be transitive — that non-transitivity is the whole source of the phenomenon. -/
structure Scenario where
  Probe   : Type
  Outcome : Probe → Type
  Context : Type
  member  : Context → Probe → Prop

variable (S : Scenario)

/-- An answer to every probe at once: the classical "hidden state". -/
def Assignment := (q : S.Probe) → S.Outcome q

/-- An answer to just the probes of one context: what you can actually obtain
    in a single act of measurement. -/
def Sect (C : S.Context) := (q : S.Probe) → S.member C q → S.Outcome q

/-- Restricting a global assignment to what one context can see. -/
def restrict (C : S.Context) (g : Assignment S) : Sect S C :=
  fun q _ => g q

/-- A possibilistic object: for each context, which local answers are possible.
    This is the PZFC notion of "set" with the Sharp dial left on and the
    probability dial replaced by mere support. -/
structure Model where
  support : (C : S.Context) → Sect S C → Prop

variable {S}

/-- No-signalling, possibilistic form: what is possible in a smaller context is
    inherited from what is possible in a larger one.  This is the *local*
    coherence that classical frameworks silently upgrade to global existence. -/
def Model.Compatible (M : Model S) : Prop :=
  ∀ (C C' : S.Context) (sub : ∀ q, S.member C' q → S.member C q)
    (s : Sect S C), M.support C s → M.support C' (fun q h => s q (sub q h))

/-- (GLU) for a single object: the local data do come from one global object. -/
def Model.HasGlobalSection (M : Model S) : Prop :=
  ∃ g : Assignment S, ∀ C : S.Context, M.support C (restrict S C g)

/-- Strong contextuality: not one global assignment is everywhere possible.
    `CF = 1` in src/pzfc/contextual.py. -/
def Model.StronglyContextual (M : Model S) : Prop :=
  ∀ g : Assignment S, ∃ C : S.Context, ¬ M.support C (restrict S C g)

theorem Model.not_both (M : Model S) :
    M.HasGlobalSection → ¬ M.StronglyContextual := by
  rintro ⟨g, hg⟩ hsc
  obtain ⟨C, hC⟩ := hsc g
  exact hC (hg C)

/-- The probe complex is a simplex: some single context sees every probe.
    "Linear time + perfect record" is of this shape — every past observation is
    assumed to be simultaneously readable and undisturbed, hence co-measurable. -/
def Scenario.IsSimplex (S : Scenario) : Prop :=
  ∃ C₀ : S.Context, ∀ q : S.Probe, S.member C₀ q

/-!
### The main lemma

On a simplex, local coherence *is* global existence: there is nothing for an
obstruction class to measure.
-/

theorem simplex_glues
    (M : Model S) (hM : M.Compatible)
    (C₀ : S.Context) (hcov : ∀ q, S.member C₀ q)
    (s₀ : Sect S C₀) (hs₀ : M.support C₀ s₀) :
    M.HasGlobalSection := by
  refine ⟨fun q => s₀ q (hcov q), fun C => ?_⟩
  exact hM C₀ C (fun q _ => hcov q) s₀ hs₀

/-- Contrapositive, in the form one actually wants to quote: a simplex can
    never exhibit strong contextuality (unless the object is empty outright). -/
theorem simplex_not_strongly_contextual
    (M : Model S) (hM : M.Compatible)
    (C₀ : S.Context) (hcov : ∀ q, S.member C₀ q)
    (s₀ : Sect S C₀) (hs₀ : M.support C₀ s₀) :
    ¬ M.StronglyContextual :=
  M.not_both (simplex_glues M hM C₀ hcov s₀ hs₀)

/-!
### Recovery, easy direction

Every classical object — one that *is* a global assignment — satisfies GLU.
This is the `Sharp + GLU + WF` corner of notes/01 §1 seen from inside.
-/

/-- The object generated by a single global state: a static lookup table. -/
def classical (g : Assignment S) : Model S where
  support := fun C s => s = restrict S C g

theorem classical_compatible (g : Assignment S) :
    (classical g).Compatible := by
  intro C C' sub s hs
  cases hs
  rfl

theorem classical_hasGlobalSection (g : Assignment S) :
    (classical g).HasGlobalSection :=
  ⟨g, fun _ => rfl⟩

/-!
### What is deliberately *not* here

* the Sharp dial — `support : Sect → Prop` is already 0/1 valued.
  Turning it off means replacing `Prop` by an effect algebra, at which point
  `simplex_glues` should survive and `not_both` should become quantitative.
* the WF dial — `Assignment` is a function type, hence well-founded by fiat.
  Turning it off means replacing it by the final coalgebra of the no-signalling
  functor, which is open problem O1 in notes/04.
* anything probabilistic — that is src/pzfc/, and it is exact-rational there
  precisely so that "is the obstruction zero" stays a decidable question.
-/

end PZFC
