/-
  The shape of the base B (notes/55, 103) and the validity of the method of changing worlds.
  Mathlib-free.

  A multiverse has worlds, an extension preorder, sentences (with parameters), satisfaction,
  and a predicate saying which sentences have their parameters available in a world
  (parameters, once present, stay present).  A distinguished class of *core* sentences (those
  about the countable core H(ω₁), or under M4⁺ about L(ℝ)) is invariant along extensions:
  this is axiom M4.  Worlds are closed under a sound derivability relation (each world is a
  model of the ambient logic plus its axioms).

  §1  the structure
  §2  changing worlds: to prove a core sentence in a world, it suffices to prove it in some
      extension, possibly using hypotheses that are only true there (e.g. CH, or a collapse)
  §3  core sentences are global; their modal status is trivial (Triv, notes/76)
  §4  sentences that can be forced both ways are local
  §5  worlds with a common extension agree on core sentences
  §6  theory-directedness gives the principle .2 for sentences (notes/104)
  §7  two tiers (notes/106): if the core of B⁺ (sentences about L(ℝ)) contains the core of B
      (sentences about H(ω₁)), everything proved for the larger core holds for the smaller
-/

namespace PZFC.Worlds

/-! ## 1. The structure -/

/-- A multiverse of worlds with extensions (the shape of M1–M4). -/
structure Multiverse where
  World : Type
  Sent : Type
  /-- `ext u v`: `v` is an extension of `u` (generated by width and height steps). -/
  ext : World → World → Prop
  ext_refl : ∀ w, ext w w
  ext_trans : ∀ {u v x : World}, ext u v → ext v x → ext u x
  /-- Satisfaction in a world. -/
  sat : World → Sent → Prop
  /-- The parameters of the sentence exist in the world. -/
  avail : Sent → World → Prop
  avail_mono : ∀ {φ : Sent} {u v : World}, ext u v → avail φ u → avail φ v
  /-- Sentences about the countable core. -/
  core : Sent → Prop
  /-- M4: core sentences with available parameters do not change along extensions. -/
  m4 : ∀ {φ : Sent} {u v : World}, core φ → ext u v → avail φ u → (sat u φ ↔ sat v φ)
  /-- Derivability (from a list of hypotheses), sound in every world. -/
  Derives : List Sent → Sent → Prop
  sound : ∀ (w : World) {Γ : List Sent} {φ : Sent}, Derives Γ φ → (∀ ψ ∈ Γ, sat w ψ) → sat w φ

variable (M : Multiverse)

/-! ## 2. Changing worlds -/

/-- The basic form: a core sentence true in some extension is already true. -/
theorem change_worlds {w v : M.World} {φ : M.Sent} (hc : M.core φ) (ha : M.avail φ w)
    (hwv : M.ext w v) (hv : M.sat v φ) : M.sat w φ :=
  (M.m4 hc hwv ha).2 hv

/-- The working form: to prove a core sentence `φ` in `w`, pass to an extension `v` in which
some extra hypotheses `Γ` hold (for instance CH, or "this set is countable"), derive `φ` there
from `Γ`, and bring it back. -/
theorem change_worlds_derive {w v : M.World} {Γ : List M.Sent} {φ : M.Sent} (hc : M.core φ)
    (ha : M.avail φ w) (hwv : M.ext w v) (hΓ : ∀ ψ ∈ Γ, M.sat v ψ) (hd : M.Derives Γ φ) :
    M.sat w φ :=
  change_worlds M hc ha hwv (M.sound v hd hΓ)

/-! ## 3. Core sentences are global and modally trivial -/

/-- A sentence is global when its truth never changes along extensions. -/
def Global (φ : M.Sent) : Prop :=
  ∀ {u v : M.World}, M.ext u v → M.avail φ u → (M.sat u φ ↔ M.sat v φ)

theorem global_of_core {φ : M.Sent} (hc : M.core φ) : Global M φ :=
  fun huv ha => M.m4 hc huv ha

/-- Necessity: true in every extension. -/
def Box (w : M.World) (φ : M.Sent) : Prop := ∀ v, M.ext w v → M.sat v φ

/-- Possibility: true in some extension. -/
def Dia (w : M.World) (φ : M.Sent) : Prop := ∃ v, M.ext w v ∧ M.sat v φ

/-- On global sentences the modalities collapse: `φ ↔ □φ ↔ ◇φ` (the logic Triv). -/
theorem triv_of_global {w : M.World} {φ : M.Sent} (hg : Global M φ) (ha : M.avail φ w) :
    (M.sat w φ ↔ Box M w φ) ∧ (M.sat w φ ↔ Dia M w φ) := by
  constructor
  · constructor
    · intro h v hv; exact (hg hv ha).1 h
    · intro h; exact h w (M.ext_refl w)
  · constructor
    · intro h; exact ⟨w, M.ext_refl w, h⟩
    · rintro ⟨v, hv, h⟩; exact (hg hv ha).2 h

/-! ## 4. Local sentences -/

/-- A sentence that can be made true in one extension and false in another is not global;
in particular it is not a core sentence (e.g. CH, notes/55 §3.6). -/
theorem not_global_of_split {w v₁ v₂ : M.World} {φ : M.Sent} (ha : M.avail φ w)
    (h1 : M.ext w v₁) (h2 : M.ext w v₂) (hv₁ : M.sat v₁ φ) (hv₂ : ¬ M.sat v₂ φ) :
    ¬ Global M φ := by
  intro hg
  exact hv₂ ((hg h2 ha).1 ((hg h1 ha).2 hv₁))

theorem not_core_of_split {w v₁ v₂ : M.World} {φ : M.Sent} (ha : M.avail φ w)
    (h1 : M.ext w v₁) (h2 : M.ext w v₂) (hv₁ : M.sat v₁ φ) (hv₂ : ¬ M.sat v₂ φ) :
    ¬ M.core φ :=
  fun hc => not_global_of_split M ha h1 h2 hv₁ hv₂ (global_of_core M hc)

/-! ## 5. Worlds with a common extension agree on the core -/

/-- Two worlds that have a common extension agree on core sentences whose parameters both
contain.  (No amalgamation is assumed in B; this only says what happens when it exists.) -/
theorem agree_of_common {u v x : M.World} {φ : M.Sent} (hc : M.core φ) (hux : M.ext u x)
    (hvx : M.ext v x) (hu : M.avail φ u) (hv : M.avail φ v) : M.sat u φ ↔ M.sat v φ :=
  (M.m4 hc hux hu).trans (M.m4 hc hvx hv).symm

/-! ## 6. Theory-directedness gives .2 for sentences -/

/-- `w` is theory-directed: any two extensions can be extended further to worlds that agree
on every sentence whose parameters are available in `w`. -/
def TheoryDirected (w : M.World) : Prop :=
  ∀ u v, M.ext w u → M.ext w v →
    ∃ u' v', M.ext u u' ∧ M.ext v v' ∧ ∀ φ, M.avail φ w → (M.sat u' φ ↔ M.sat v' φ)

/-- `.2`: if some extension makes `φ` necessary, then every extension can still reach `φ`. -/
theorem dot2 {w : M.World} (hd : TheoryDirected M w) {φ : M.Sent} (ha : M.avail φ w)
    (h : ∃ u, M.ext w u ∧ Box M u φ) : ∀ v, M.ext w v → Dia M v φ := by
  obtain ⟨u, hwu, hbox⟩ := h
  intro v hwv
  obtain ⟨u', v', huu', hvv', hagree⟩ := hd u v hwu hwv
  exact ⟨v', hvv', (hagree φ ha).1 (hbox u' huu')⟩

/-! ## 7. Two tiers -/

/-- A smaller class of sentences inside the core (for B: sentences about `H(ω₁)`, inside the
core of B⁺: sentences about `L(ℝ)`) is invariant along extensions: M4⁺ implies M4. -/
theorem m4_of_sub {core₀ : M.Sent → Prop} (hsub : ∀ φ, core₀ φ → M.core φ) {φ : M.Sent}
    (h0 : core₀ φ) {u v : M.World} (huv : M.ext u v) (ha : M.avail φ u) :
    M.sat u φ ↔ M.sat v φ :=
  M.m4 (hsub φ h0) huv ha

/-- Changing worlds for the smaller core. -/
theorem change_worlds_sub {core₀ : M.Sent → Prop} (hsub : ∀ φ, core₀ φ → M.core φ)
    {w v : M.World} {φ : M.Sent} (h0 : core₀ φ) (ha : M.avail φ w) (hwv : M.ext w v)
    (hv : M.sat v φ) : M.sat w φ :=
  change_worlds M (hsub φ h0) ha hwv hv

end PZFC.Worlds
